// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "http://localhost:54321";
const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "public-anon-key";

type SupabaseAuthConfig = {
  storage?: Storage;
  persistSession: boolean;
  autoRefreshToken: boolean;
};

type SupabaseClientLike<TDatabase> = {
  url: string;
  key: string;
  options: { auth: SupabaseAuthConfig };
  __db?: TDatabase;
};

const createClient = <TDatabase,>(
  url: string,
  key: string,
  options: { auth: SupabaseAuthConfig },
): SupabaseClientLike<TDatabase> => {
  return { url, key, options };
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
